services:
  airguard:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      WAQI_TOKEN: ${WAQI_TOKEN}
      OPENWEATHER_KEY: ${OPENWEATHER_KEY}
